map-reset-floor: gray_concrete
# The amount of ticks that it should take for a dynamite to explode.
dynamite-explode-ticks: 10
# In minutes
map-reset-cooldown: 30

coin-block: gold_ore
op-coin-block: gold_block
coins-per-coin-block-mined: 0.5
coins-per-op-coin-block-mined: 30
coins-per-player-killed: 5
coins-earned-message: "<#1a8739>You earned <#ebd728><amount> coins! <#1a8739>Spend them at the merchants at spawn!"
not-enough-coins-for-withdrawal: "<red>You cannot withdraw <yellow><amount></yellow> coins because you only have <yellow><balance></yellow> available!"
withdrawal-success: "<green>You successfully withdrew <yellow><amount></yellow>! Your balance is now <yellow><balance></yellow>"
withdrawal-used: "<green>You used the withdrawal and gained <yellow><amount></yellow>! Your balance is now <yellow><balance></yellow>"
cannot-withdraw-invalid-amount: "<red>You cannot withdraw <yellow><amount></yellow> because it is less than or equal to zero!"

kit-settings:
  weapons:
    items:
      - material: diamond_sword
        enchantments:
          - name: sharpness
            levels: [1, 2, 3, 4]

      - material: netherite_sword
        enchantments:
          - name: sharpness
            levels: [1, 2, 3]

      - material: trident
        enchantments:
          - name: loyalty
            levels: [1, 2, 3]
          - name: sharpness
            levels: [1, 2, 3, 4]

  helmets:
    items:
      - material: iron_helmet
        enchantments:
          - name: protection
            levels: [4]

      - material: diamond_helmet
        enchantments:
          - name: protection
            levels: [1, 2, 3]

      - material: netherite_helmet
        enchantments:
          - name: protection
            levels: [1, 2]

  chestplates:
    items:
      - material: iron_chestplate
        enchantments:
          - name: protection
            levels: [4]

      - material: diamond_chestplate
        enchantments:
          - name: protection
            levels: [1, 2, 3]

      - material: netherite_chestplate
        enchantments:
          - name: protection
            levels: [1, 2]

  leggings:
    items:
      - material: iron_leggings
        enchantments:
          - name: protection
            levels: [4]

      - material: diamond_leggings
        enchantments:
          - name: protection
            levels: [1, 2, 3]

      - material: netherite_leggings
        enchantments:
          - name: protection
            levels: [1, 2]

  boots:
    items:
      - material: iron_boots
        enchantments:
          - name: protection
            levels: [4]

      - material: diamond_boots
        enchantments:
          - name: protection
            levels: [1, 2, 3]

      - material: netherite_boots
        enchantments:
          - name: protection
            levels: [1, 2]

  tools:
    max-items: 2
    items:
      - material: diamond_pickaxe
        enchantments:
          - name: efficiency
            levels: [1, 2, 3]

      - material: diamond_axe
        enchantments:
          - name: sharpness
            levels: [1, 2, 3]
          - name: efficiency
            levels: [1, 2]

  ranged-Weapons:
    items:
      - material: bow
        items:
          - material: arrow
            amount: 16
        enchantments:
          - name: power
            levels: [1, 2, 3]

      - material: crossbow
        items:
          - material: firework_rocket
            firework:
              flight-duration: 127
              explosions:
                - shape: creeper
                  colors: "#00ff7f"
                  fade-colors: "#000000"
                  has-trail: true
                  has-twinkle: false
            amount: 8
        enchantments:
          - name: quick_charge
            levels: [1, 2, 3]
          - name: multishot
            levels: [1]

  food:
    max-items: 1
    items:
      - material: cooked_beef
        amount: [4, 8, 16]
      - material: golden_apple
        amount: [1, 2]

  offhand:
    items:
      - material: shield
      - material: totem_of_undying

  misc:
    min-items: 0
    items:
      - material: red_candle
        name: "<red>Dynamite"
        pdc: "dynamite"
        amount: [1, 2, 4]
      - material: ender_pearl
        amount: [1, 2]
      - material: light_blue_dye
        pdc: "haste_talisman"
        name: "<aqua>Haste Talisman"
        offhand-effects:
          - id: haste
            amplifier: 1
            duration: 1