map-reset-floor: gray_concrete
# The amount of ticks that it should take for a dynamite to explode.
dynamite-explode-ticks: 15
# In minutes
map-reset-cooldown: 20
# The type of the coin block that will spawn in map resets
coin-block: gold_ore
op-coin-block: gold_block
# How many coins (as a decimal) a player should get when mining a block of the type of the coin block
coins-per-coin-block-mined: 0.5
coins-per-op-coin-block-mined: 30
# How many coins a player gets when killing another player
coins-per-player-killed: 5
coins-earned-message: "<#1a8739>You earned <#ebd728><amount> coins! <#1a8739>Spend them at the merchants at spawn!"
not-enough-coins-for-withdrawal: "<red>You cannot withdraw <yellow><amount></yellow> coins because you only have <yellow><balance></yellow> available!"
cannot-withdraw-invalid-amount: "<red>You cannot withdraw <yellow><amount></yellow> because it is less than or equal to zero!"
withdrawal-success: "<green>You successfully withdrew <yellow><amount></yellow>! Your balance is now <yellow><balance></yellow>"
withdrawal-used: "<green>You used the withdrawal and gained <yellow><amount></yellow>! Your balance is now <yellow><balance></yellow>"

kit-settings:
  weapons:
    items:
      - material: diamond_sword
        enchantments:
          sharpness: [1, 2, 3]

      - material: netherite_sword
        enchantments:
          sharpness: [1, 2, 3]

      - material: trident
        enchantments:
          loyalty: [1]

  helmets:
    items:
      - material: diamond_helmet
        enchantments:
          protection: [1, 2]

      - material: netherite_helmet
        enchantments:
          protection: [1, 2]

  chestplates:
    items:
      - material: diamond_chestplate
        enchantments:
          protection: [1, 2]

      - material: netherite_chestplate
        enchantments:
          protection: [1, 2]

  leggings:
    items:
      - material: diamond_leggings
        enchantments:
          protection: [1, 2]

      - material: netherite_leggings
        enchantments:
          protection: [1, 2]

  boots:
    items:
      - material: diamond_boots
        enchantments:
          protection: [1, 2]

      - material: netherite_boots
        enchantments:
          protection: [1, 2]

  tools:
    max-items: 2
    items:
      - material: diamond_pickaxe
        enchantments:
          efficiency: [1, 2]

      - material: diamond_axe
        enchantments:
          sharpness: [1]
          efficiency: [1]

  ranged-Weapons:
    items:
      - material: bow
        items:
          - material: arrow
            amount: 16
        enchantments:
          power: [1, 2]

      - material: crossbow
        items:
          - material: arrow
            amount: 8
        enchantments:
          quick_charge: [1, 2, 3]

  food:
    items:
      - material: cooked_beef
        amount: [4, 8, 16]

  offhand:
    items:
      - material: shield
      - material: totem_of_undying

  blocks:
    items:
      - material: cobblestone
        amount: 64
      - material: oak_planks
        amount: 64

  misc:
    min-items: 0
    items:
      - material: red_candle
        name: "<red>Dynamite"
        pdc: "dynamite"
        amount: [1, 2]
      - material: splash_potion
        potion_contents:
          color: "#00ff7f"
          effects:
            - id: strength
              amplifier: 2
              # Duration in seconds
              duration: 30
              ambient: false
              show_particles: false
              show_icon: false
      - material: light_blue_dye
        offhand-effects:
          - id: haste
            amplifier: 1
            duration: 1
